---
logger-info:
   logger-name: "soundrecorder"
   filehandler-data:
      include: true
      level: "INFO"
      log-Location: "/home/user1/scripts/logs"
   gmailhandler-data:
     include: false
   dbhandler-data:
      include: false
soundrecorder-info:
   run-minutes: ~
   device-index: 6
   format: 8
   sample-rate: 48000
   chunk: 1000
   channels: 1
   input: true
   delete-old: true
   output-name: 'nsrt'
   dest-dir: '/mnt/share/user2/SoundRecord'
   network-share: '//192.168.1.281/shared'
   local-mount: '/mnt/share'
   credentials-file: '/home/user2/.smbcredentials'

